# Generated by Django 4.1.7 on 2023-04-30 01:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name='Medication'),
       

    ]
