# Generated by Django 4.1.7 on 2023-04-30 01:20

from django.db import migrations, models
import django.utils.timezone
class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_auto_20230429_2015"),
    ]

    operations = [
          migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("patientId", models.CharField(max_length=255)),
                ("medication", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=50)),
                ("dateIssued", models.DateField(default=django.utils.timezone.now)),
                ("instructions", models.CharField(max_length=50)),
            ],
        ),
    ]
